name: "Build and upload helps"

on:
    create:
    push:
      branches: [main]


jobs:
    build-apps:
        name: "Build Apps"
        runs-on: ubuntu-latest
        outputs:
          help_modified: ${{steps.changes.outputs.help_modified}}
        steps:

          - name: Checkout Web-Apps
            uses: actions/checkout@v3
            with:
                repository: onlyoffice/web-apps
                ref: ${{github.ref}}
                path: 'web-apps'

          - name: Path filter for help
            if: (startsWith(github.ref, 'refs/heads/release/') ||
             startsWith(github.ref, 'refs/heads/hotfix/'))
            uses: dorny/paths-filter@v2
            id: changes
            with:
              working-directory: 'web-apps'
              base: ${{github.ref}}
              initial-fetch-depth: '1'
              filters: |
                help_modified:
                  - added|deleted|modified: '**/resources/help/**'

          - name: Determine branch variable
            run: |
              if ${{steps.changes.outputs.help_modified == 'true'}}; then
                echo "REF=${{ github.ref }}" >> $GITHUB_ENV
              else
                echo "REF=develop" >> $GITHUB_ENV
              fi

          - name: Checkout SDKJS
            uses: actions/checkout@v3
            with:
                repository: onlyoffice/sdkjs
                token: ${{ secrets.READ_PAT }}
                ref: ${{env.REF}}
                path: 'sdkjs'
                fetch-depth: '1'
              
          - name: Use Node.js 16
            uses: actions/setup-node@v3
            with:
                node-version: 16   

          - name: Build
            run: |
                cd web-apps/build
                ./sprites.sh
                npm install
                grunt

          - name: Apps files
            id: apps-files
            if: steps.changes.outputs.help_modified == 'true'
            run: tar -cvf apps.tar ./web-apps/deploy/web-apps/apps

          - name: Upload artifact
            if: steps.apps-files.outcome == 'success'
            uses: actions/upload-artifact@v3
            with:
              name: apps-artifact
              path: apps.tar
